### ISSUE TITLE
4.13.x demo missing content in frontend

### ISSUE THREAD

**Issue by Kyuhunter** [contao/contao-demo#26]
The 4.13.x demo seems to be broken. It is not showing all the content elements in the frontend. Only the header and footer are showing up correctly, and the menu is broken/missing.
<img width="1728" alt="image" src="https://github.com/contao/contao-demo/assets/44449951/10d11ebd-a04b-4abb-9801-b9d2fc759ac2">

I have reproduced this issue on:
- macOS with DDEV
- macOS with Devilbox
- Windows 10 with DDEV

The problem also occurs regardless of which installation method I choose (via terminal or contao manager).

**Comment by zoglo** [comment]
@Kyuhunter should be fixed in this here:
https://github.com/contao/contao-demo/pull/24

Could you try the following sql dump, move it into `var/backups` and 
```contao:backup:restore``` 
from there and see if it's still the same?
https://github.com/contao/contao-demo/blob/a529759dc69744448e362ca5644608a2f4e5ea5a/var/backups/backup__20240227191303.sql.gz

**Comment by Kyuhunter** [comment]
@zoglo Yes, this fixed it!

**Comment by Tastaturberuf** [comment]
Yes, the actual 4.13 demo is broken. @zoglo ~this backup dosnt work for me.~ it fixed this problem.i was in the wrong folder.

**Comment by aschempp** [comment]
Should be fixed in the latest release.
